image: python:3.9

variables:
  # Replace with a personal access token if needed
  GITLAB_TOKEN: $CI_JOB_TOKEN

before_script:
  - conda activate documentation_mkdocs
  # Install MkDocs and dependencies
  - pip install mkdocs mkdocs-material

pages:
  tags:
    - untagged
  script:
    # Build the MkDocs site
    - mkdocs build
  only:
    - master  # Adjust to match your default branch
