# Long-read data
experiment: "ModRefGenome_Magdeburg_sup_Vector_integration_site"
samples:
    #full_CD123+: "/home/weichan/permanent/Projects/VIS/dev/CD123_sup_dorado_ref.bam"
    #full_Cd123+: "/home/weichan/permanent/Projects/VIS/dev/cd123+/gfp_pos_native.fq.gz" #nanopolish idnex file sin folder
    #full_ads: "/home/weichan/permanent/Projects/VIS/dev/ads/gfp_pos_ads.fq.gz"
    #full_ads: "/home/weichan/permanent/Projects/VIS/dev/ADS_sup_dorado_ref.bam" #bam from dorado with reference an mod bases option
    #full_ads: "/home/weichan/permanent/Projects/VIS/dev/gfp_pos_ads.fq.gz"
    #UTD: "/home/lischecr/temporary/NanoporeData/VIS/UTD/utd.native.fq.gz"
    #UTD: "/home/weichan/permanent/Projects/VIS/dev/UTD_sup_dorado_ref.bam"
    #dummy: "/home/weichan/permanent/Projects/VIS/dev/DummyData.fa"
    #S1: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/S1_sup_dorado_ref.bam" #CD19
    #S2: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/S2_sup_dorado_ref.bam"
    S3: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/S3_sup_dorado_ref.bam"
    S4: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/S4_sup_dorado_ref.bam"
processing_dir: "/home/weichan/permanent/Projects/VIS/VIS_integration_site/Results"
source_dir: "/home/weichan/permanent/Projects/VIS/VIS_integration_site/Src"
#vector_fasta: "/home/weichan/permanent/Projects/VIS/dev/DummyVector.fa" #
#vector_fasta: "/home/weichan/permanent/Projects/VIS/dev/cd123_car_ref.fa"
vector_fasta: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/pSLCAR-CD19-28z.fasta"
blastn_db: "/home/weichan/blastNdb/blastNdb" #human nucleotides to see which parts of the human genome match the CAR construct
fragment_size: 100 #input for custom function
MinLength: 66
#ref_genome: "/home/lischecr/permanent/Src/hg38/genome/hg38.fa"
ref_genome: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/hg38_CD19.fasta"
#ref_genome_index: "/home/lischecr/permanent/Src/hg38/genome/hg38.ref.mmi" #minimap output
#methylation call
#fast5path: "/home/weichan/permanent/Projects/VIS/dev/ads/pod5tofast5/" #only ads currently
#sequencingsummary: "/home/lischecr/temporary/NanoporeData/VIS/GFP_POS_ADS/20230602_1106_MN37858_FAW82898_dd8938f8/sequencing_summary_FAW82898_dd8938f8_c07a3414.txt"

