# Long-read data
experiment: "Barcoded_BBz" #"CD123_filter_eef1a_Vector_integration_site"Full_CD19_filter_cd247_Vector_integration_site"DummyExample"#change the threshhold fro CD19 and CD123 and location plos
samples:
    #full_CD123+: "/home/weichan/permanent/Projects/VIS/dev/CD123/CD123_sup_dorado_ref.bam"
    #full_ads: "/home/weichan/permanent/Projects/VIS/dev/CD123/ADS_sup_dorado_ref.bam" #bam from dorado with reference an mod bases option
    #full_ads: "/home/weichan/permanent/Projects/VIS/dev/gfp_pos_ads.fq.gz"
    #UTD: "/home/lischecr/temporary/NanoporeData/VIS/UTD/utd.native.fq.gz"
    #UTD: "/home/weichan/permanent/Projects/VIS/dev/CD123/UTD_sup_dorado_ref.bam"
    #GFP+_CD123_pooled: "/home/weichan/permanent/Projects/VIS/dev/CD123/Pooled_CD123_GFP+.bam"
    #dummy: "/home/weichan/permanent/Projects/VIS/dev/DummyData.fa"
    #S1: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/S1_sup_dorado_ref.bam" #CD19
    #S2: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/S2_sup_dorado_ref.bam"
    #S3: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/20231211_1304_MN35428_FAW87932_7d66ac35/S3_sup_dorado_ref.bam"
    #S4: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/20231211_1304_MN37858_FAX97335_cdcfc2d8/S4_sup_dorado_ref.bam"
    #S4r: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/20240115_1540_MN40944_FAW84844_01854254/S4_sup_dorado_ref.bam"
    #S3r: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/20240122_1254_MN37858_FAX66721_25279206/S3_sup_dorado_ref.bam"
    #S4_ADS: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/ADS_S4/ADS_S4_sup_dorado_ref.bam"
    #S3_pooled: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/Pooled_S3.bam"
    #S4_pooled: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/Pooled_S4.bam"
    #MK025_GFP+: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg/20240205_1448_MN35428_FAX66700_46d2ede9/MK025_GFPpos_sup_dorado_ref.bam"
    #Dummy: "/home/weichan/permanent/Projects/VIS/dev/minimum_example/RandomLongReadsWithInsertions.bam"
    #MK014_28z: "/home/weichan/permanent/Projects/VIS/dev/VIS_MPX_1/Barcoded/Demux/SQK-RBK114-24_barcode03.bam"
    #MK025_28z: "/home/weichan/permanent/Projects/VIS/dev/VIS_MPX_1/Barcoded/Demux/SQK-RBK114-24_barcode07.bam"
    #MK028_28z: "/home/weichan/permanent/Projects/VIS/dev/VIS_MPX_1/Barcoded/Demux/SQK-RBK114-24_barcode11.bam"
    #MK014_UTC: "/home/weichan/permanent/Projects/VIS/dev/VIS_MPX_1/Barcoded/Demux/SQK-RBK114-24_barcode02.bam"
    #MK025_UTC: "/home/weichan/permanent/Projects/VIS/dev/VIS_MPX_1/Barcoded/Demux/SQK-RBK114-24_barcode06.bam"
    #MK028_UTC: "/home/weichan/permanent/Projects/VIS/dev/VIS_MPX_1/Barcoded/Demux/SQK-RBK114-24_barcode10.bam"
    MK014_BBz: "/home/weichan/permanent/Projects/VIS/dev/VIS_MPX_1/Barcoded/Demux/SQK-RBK114-24_barcode03.bam"
    MK025_BBz: "/home/weichan/permanent/Projects/VIS/dev/VIS_MPX_1/Barcoded/Demux/SQK-RBK114-24_barcode07.bam"
    MK028_BBz: "/home/weichan/permanent/Projects/VIS/dev/VIS_MPX_1/Barcoded/Demux/SQK-RBK114-24_barcode11.bam"
processing_dir: "/home/weichan/permanent/Projects/VIS/VIS_integration_site/Results"
source_dir: "Src/"
#vector_fasta: "/home/weichan/permanent/Projects/VIS/dev/DummyVector.fa"
#vector_fasta: "/home/weichan/permanent/Projects/VIS/dev/CD123/cd123_car_ref.fa"
#vector_fasta: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg_withBasecalling/pSLCAR-CD19-28z.fasta"
vector_fasta: "/home/weichan/permanent/Projects/VIS/dev/pSLCAR-CD19-BBz/pSLCAR-CD19-BBz.fa"
blastn_db: "/home/weichan/blastNdb/blastNdb" #human nucleotides to see which parts of the human genome match the CAR construct
# protein BLASTp database
proteindb: "/home/weichan/swissprot/swissprot"
fragment_size: 100 #input for custom function
MinLength: 1
MinInsertionLength: 500 #212 eef1a length,cd247 1600nt. 1182 in car123 maybe 1200 with buffer?
ref_genome_ctrl: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg_withBasecalling/hg38.fa"
#ref_genome: "/home/weichan/permanent/Projects/VIS/dev/CD123/hg38_CD123.fasta" #might still contain empty last row!
#ref_genome: "/home/weichan/permanent/Projects/VIS/dev/VIS_Magdeburg_withBasecalling/hg38_CD19.fasta"
ref_genome: "/home/weichan/permanent/Projects/VIS/dev/pSLCAR-CD19-BBz/hg38_CD19_BBz.fa"
#ucsc_repeats: "/home/weichan/permanent/Projects/VIS/dev/UCSC/UCSC_RepeatMasker_02_24"
ucsc_H3K4Me1: "/home/weichan/permanent/Projects/VIS/dev/UCSC/UCSC_LayeredH3K4Me1_02_24"
ucsc_H3K27Ac: "/home/weichan/permanent/Projects/VIS/dev/UCSC/UCSC_LayeredH3K27Ac_02_24"
ucsc_H3K4Me3: "/home/weichan/permanent/Projects/VIS/dev/UCSC/UCSC_LayeredH3K4Me3_02_24"
#ucsc_DNaseH: "/home/weichan/permanent/Projects/VIS/dev/UCSC/UCSC_DNaseClusters_02_24_cut"
ucsc_TF: "/home/weichan/permanent/Projects/VIS/dev/UCSC/UCSC_TFClusters_02_24_cut_1000"
ucsc_Genes: "/home/weichan/permanent/Projects/VIS/dev/UCSC/UCSC_AllGENCODEV44_02_24_mod"
ucsc_Genes_gtf: "/home/weichan/permanent/Projects/VIS/dev/UCSC/gencode.v44.annotation.gtf"
#epigenetics rule collection
epigenetics: "./Src/epigenetics.smk"
#variants rule collection
variants: "./Src/variants.smk"
#qc rule collection
quality_control: "./Src/qc.smk"
#functional genomics rule collection
functional_genomics: "./Src/functional_genomics.smk"