site_name: Vector Insertion Site Detection Pipeline
theme:
  name: material
  logo: docs/images/dag.png
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Configuration: config.md
  - Usage: usage.md
  - Tutorial: tutorial.md
  - Advanced Usage: advanced_usage.md
  - Other: other.md
markdown_extensions:
  - admonition