# tutorial config
experiment: "simulation_tutorial"
samples:
  S1: "tutorial/simulated/S1.bam"
  S2: "tutorial/simulated/S2.bam"
processing_dir: "tutorial/out"
threads: 2
insertion_fasta: "tutorial/references/vectorseq.fa"
splitmode: "Buffer"
fragment_size: 100
bridging_size: 300
MinLength: 1
MAPQ: 10
MinInsertionLength: 500
ref_genome_ctrl: "tutorial/references/chr1_1_50000_ref.fa"
annotate_ucsc_genes: "tutorial/references/UCSC_genes_chr1_0_500000_processed.bed"
detection: "rules/detection.smk"
quality_control: "rules/qc.smk"
functional_genomics: "rules/functional_genomics.smk"
