name: Snakemake Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snakemake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults

      - name: Install dependencies
        run: |
          mamba env create -f workflow/envs/VIS_minimal.yml
          eval "$(mamba shell hook --shell bash)"
          mamba activate VIS_minimal
          
      - name: Testing
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'workflow/Snakefile'
          args: '--cores 1 --use-conda -n --conda-cleanup-pkgs cache'
        env:
          CONDA_DEFAULT_ENV: VIS_minimal

