name: Snakemake Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snakemake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults

      - name: Install dependencies
        run: |
          mamba env create -f workflow/envs/VIS_minimal.yml
          eval "$(mamba shell hook --shell bash)"
          mamba activate VIS_minimal

      - name: Debug File Paths
        run: |
          echo "Current working directory: $(pwd)"
          ls -R workflow/scripts
          
      - name: Run Snakemake
        run: |
          eval "$(mamba shell hook --shell bash)"
          mamba activate VIS_minimal
          snakemake --cores 1 --configfile config/config_CD19_BBz.yml -n --use-conda
